# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_cloud', '0003_notifications_problem_share_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('DF', 'Difficult'), ('MD', 'Medium'), ('ES', 'Easy'), ('NA', 'Not Applicable')], default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='problem',
            name='online_judge',
            field=models.CharField(choices=[('CC', 'Codechef'), ('UV', 'UVa'), ('CF', 'Codeforces'), ('TC', 'Topcoder'), ('SP', 'Sphere Online Judge'), ('NA', 'Not Applicable')], max_length=200),
        ),
    ]
