# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_cloud', '0004_auto_20160402_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
